-- SET CONTEXT
USE WAREHOUSE COMPUTE_XS;
USE ROLE SYSADMIN;

-- CREATE DATABASE AND SCHEMA FOR WORKSHOP
CREATE OR REPLACE DATABASE TRAINING_WORKSHOP
  DATA_RETENTION_TIME_IN_DAYS = 1;

CREATE OR REPLACE SCHEMA TRAINING_WORKSHOP.SUPERSTORE;

-- SPECIFY SCHEMA CONTEXT FOR THE SHEET
USE SCHEMA TRAINING_WORKSHOP.SUPERSTORE

-- CREATE A STAGE TO UPLOAD FILES
CREATE STAGE TRAINING_WORKSHOP.SUPERSTORE.PARQUET_FILES_STAGE
    FILE_FORMAT = (TYPE = PARQUET);

-- CREATE A FILE FORMAT TO BE USED BY THE ICEBERG TABLES
CREATE FILE FORMAT TRAINING_WORKSHOP.SUPERSTORE.PARQUET_FORMAT
    TYPE = PARQUET;

-- UPLOAD FILES USING SNOWSIGHT

-- CHECK FILES IN THE STAGE
LS '@TRAINING_WORKSHOP.SUPERSTORE.PARQUET_FILES_STAGE';

/*
CREATE AN ICEBERG TABLE USING INFER_SCHEMA FUNCTION
THIS WILL ALLOW TO AUTOMATICALLY DETECT THE TABLE SCHEMA
*/
CREATE OR REPLACE ICEBERG TABLE TRAINING_WORKSHOP.SUPERSTORE.ORDERS_ICE
    USING TEMPLATE(
        SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
            FROM TABLE(
                INFER_SCHEMA(
                LOCATION => '@TRAINING_WORKSHOP.SUPERSTORE.DATA_STAGE/',
                FILE_FORMAT => 'PARQUET_FORMAT',
                FILES => ('superstore.parquet'),
                IGNORE_CASE => TRUE
                )
            ));

-- DESCRIBE THE TABLE TO SHOW COLUMNS DETECTED
DESCRIBE TABLE TRAINING_WORKSHOP.SUPERSTORE.ORDERS;

--MAKE SURE THE ROLE HAS EVOLVE SCHEMA PRIVILEGE IN THE TABLE
GRANT EVOLVE SCHEMA ON TABLE TRAINING_WORKSHOP.SUPERSTORE.ORDERS TO ROLE SYSADMIN;

-- ALTER THE TABLE TO ENABLE SCHEMA EVOLUTION
ALTER TABLE TRAINING_WORKSHOP.SUPERSTORE.ORDERS SET ENABLE_SCHEMA_EVOLUTION = TRUE;

-- COPY DATA FROM THE FIRST FILE, WITHOUT PROFIT COLUMN, TO THE ICEBERG TABLE
COPY INTO TRAINING_WORKSHOP.SUPERSTORE.ORDERS
    FROM '@TRAINING_WORKSHOP.SUPERSTORE.DATA_STAGE/superstore.parquet'
    FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- CHECK DATA
SELECT * FROM TRAINING_WORKSHOP.SUPERSTORE.ORDERS;

-- COPY DATA FROM THE SECOND FILE, WITH PROFIT COLUMN, TO THE ICEBERG TABLE
COPY INTO TRAINING_WORKSHOP.SUPERSTORE.ORDERS
    FROM '@TRAINING_WORKSHOP.SUPERSTORE.DATA_STAGE/superstore_w_profit.parquet'
    FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- CHECK DATA AND SCHEMA
SELECT * FROM TRAINING_WORKSHOP.SUPERSTORE.ORDERS;