-- SET CONTEXT
USE WAREHOUSE COMPUTE_XS;
USE ROLE SYSADMIN;

-- CREATE DATABASE AND SCHEMA FOR WORKSHOP
CREATE OR REPLACE DATABASE TRAINING_WORKSHOP
  DATA_RETENTION_TIME_IN_DAYS = 1;

CREATE OR REPLACE SCHEMA TRAINING_WORKSHOP.SUPERSTORE;
  

CREATE SCHEMA TIL_WORKSHOP.SUPERSTORE;
USE SCHEMA TIL_WORKSHOP.SUPERSTORE;

CREATE STAGE TIL_WORKSHOP.SUPERSTORE.DATA_STAGE
    FILE_FORMAT = (TYPE = PARQUET);

LS '@TIL_WORKSHOP.SUPERSTORE.DATA_STAGE';

CREATE FILE FORMAT TIL_WORKSHOP.SUPERSTORE.PARQUET_FORMAT
    TYPE = PARQUET;

CREATE OR REPLACE ICEBERG TABLE TIL_WORKSHOP.SUPERSTORE.ORDERS_ICE
    USING TEMPLATE(
        SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
            FROM TABLE(
                INFER_SCHEMA(
                LOCATION => '@TIL_WORKSHOP.SUPERSTORE.DATA_STAGE/',
                FILE_FORMAT => 'PARQUET_FORMAT',
                FILES => ('superstore.parquet'),
                IGNORE_CASE => TRUE
                )
            ));

DESCRIBE TABLE TIL_WORKSHOP.SUPERSTORE.ORDERS;
GRANT EVOLVE SCHEMA ON TABLE TIL_WORKSHOP.SUPERSTORE.ORDERS TO ROLE DBA;
ALTER TABLE TIL_WORKSHOP.SUPERSTORE.ORDERS SET ENABLE_SCHEMA_EVOLUTION = TRUE;

COPY INTO TIL_WORKSHOP.SUPERSTORE.ORDERS
    FROM '@TIL_WORKSHOP.SUPERSTORE.DATA_STAGE/superstore.parquet'
    FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

SELECT * FROM TIL_WORKSHOP.SUPERSTORE.ORDERS;

COPY INTO TIL_WORKSHOP.SUPERSTORE.ORDERS
    FROM '@TIL_WORKSHOP.SUPERSTORE.DATA_STAGE/superstore_w_profit.parquet'
    FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

SELECT * FROM TIL_WORKSHOP.SUPERSTORE.ORDERS;
